#!/usr/bin/env bash
# Build/refresh the unified Obsidian vault: knowledge notes + entity graph + every registered repo's
# wiki, in one folder you open in Obsidian. The wiki is already .md; this materializes the SQLite
# knowledge as notes so Obsidian's graph view shows the whole knowledge graph (no plugins).
# Two-way: edits to a memory note's first paragraph or `importance` are pushed back to the store
# BEFORE regenerating, so your edits are never clobbered.
# Usage:  vault-gen [DIR] [--no-import]        (DIR defaults to ~/.carryover/vault)
set -uo pipefail
VAULT="$HOME/Documents/carryover-vault"   # visible folder (next to your other Obsidian vaults); override with an arg
NOIMPORT=""
for arg in "$@"; do
  case "$arg" in
    --no-import) NOIMPORT=1 ;;
    -*) ;;                         # ignore other flags
    *)  VAULT="$arg" ;;
  esac
done

PY="$HOME/.headroom/venv/bin/python"; [ -x "$PY" ] || PY="$(command -v python3)"
COMEM="${COMEM:-$HOME/.carryover/co-mem}"; [ -f "$COMEM" ] || COMEM="$(dirname "$0")/co-mem"

mkdir -p "$VAULT"/knowledge "$VAULT"/entities "$VAULT"/wikis "$VAULT"/.obsidian
# minimal Obsidian config so the vault opens cleanly — written only if absent (never clobber it)
[ -f "$VAULT/.obsidian/app.json" ] || printf '{"newFileLocation":"root","attachmentFolderPath":"/"}\n' > "$VAULT/.obsidian/app.json"
[ -f "$VAULT/README.md" ] || printf '# carryover vault\n\nGenerated by carryover. `knowledge/` and `entities/` are regenerated from the memory store on every `co-vault`; edit a memory note'\''s first paragraph or `importance` and it syncs back on the next run. Everything else (facts, entities, relationships, tags) is derived and read-only. `wikis/` are symlinks to each repo'\''s wiki.\n' > "$VAULT/README.md"

# 1) import edits back FIRST — protects local edits before the overwrite
[ -z "$NOIMPORT" ] && "$PY" "$COMEM" vault-import "$VAULT" --apply >/dev/null 2>&1 || true
# 2) regenerate knowledge + entities from the store
"$PY" "$COMEM" vault "$VAULT" >/dev/null || { echo "vault-gen: export failed"; exit 1; }

# 3) refresh wiki symlinks from the registry (one per repo; last worktree wins on name collision)
reg="$HOME/.carryover/wikis.list"
if [ -f "$reg" ]; then
  while IFS= read -r d; do
    [ -n "$d" ] || continue
    if [ -d "$d/wiki" ]; then root="$d"
    elif [ "$(basename "$d")" = "wiki" ] && [ -d "$d" ]; then root="$(dirname "$d")"
    else continue; fi
    # real repo name (git remote), else the folder name  # ponytail: basename is fine for a label
    label="$(git -C "$root" remote get-url origin 2>/dev/null | sed -E 's#/$##; s#.*/##; s#\.git$##')"
    [ -n "$label" ] || label="$(basename "$root")"
    ln -sfn "$root/wiki" "$VAULT/wikis/$label"
  done < "$reg"
fi
# drop dead symlinks (repo/worktree gone)
find "$VAULT/wikis" -maxdepth 1 -type l ! -exec test -e {} \; -delete 2>/dev/null || true

# 4) register the vault with Obsidian so it shows up in the vault switcher (macOS) — idempotent
OBS_CFG="$HOME/Library/Application Support/obsidian/obsidian.json"
[ -f "$OBS_CFG" ] && "$PY" - "$OBS_CFG" "$VAULT" <<'PY' || true
import json, os, sys, secrets, time, shutil
cfg, vault = sys.argv[1], os.path.realpath(os.path.expanduser(sys.argv[2]))
try:
    d = json.load(open(cfg))
except Exception:
    d = {}
vaults = d.setdefault("vaults", {})
if not any(os.path.realpath(v.get("path", "")) == vault for v in vaults.values()):
    shutil.copy(cfg, cfg + ".carryover-bak")          # back up before touching another app's config
    vaults[secrets.token_hex(8)] = {"path": vault, "ts": int(time.time() * 1000)}
    json.dump(d, open(cfg, "w"), indent=2)
    print("   Registered with Obsidian — pick it from the vault switcher (restart Obsidian if open).")
PY

n="$("$PY" "$COMEM" stats 2>/dev/null || echo '?')"
echo "💼 vault: ${n} memories + wikis → $VAULT"
echo "   Open in Obsidian:  co-vault-open   (or pick 'vault' in Obsidian's vault switcher)"
